version: 2
jobs:
  build:
    working_directory: ~/transifex/transifex-client
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      TOX_PY27: 2.7.13
      TOX_PY35: 3.5.5
      TOX_PY36: 3.6.5
      TOX_PY37: 3.7-dev
    # To see the list of pre-built images that CircleCI provides for most
    # common languages see
    # https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: randomknowledge/docker-pyenv-tox:latest
    steps:
    # Machine Setup
    #   If you break your build into multiple jobs with workflows, you will
    #   probably want to do the parts of this that are relevant in each The
    #   following `checkout` command checks out your code to your working
    #   directory. In 1.0 we did this implicitly. In 2.0 you can choose where
    #   in the course of a job your code should be checked out.
    - checkout
    # Prepare for artifact and test results  collection equivalent to how it
    # was done on 1.0. In many cases you can simplify this from what is
    # generated here. See docs on artifact collection here
    # https://circleci.com/docs/2.0/artifacts/
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    # Restore the dependency cache
    - restore_cache:
        keys:
        # This branch if available
        - txclient-{{ .Branch }}-
        # Default branch if not
        - txclient-devel-
        # Any branch if there are none on the default branch - this should be
        # unnecessary if you have your default branch configured correctly
        - txclient-
    # This is based on your 1.0 configuration file or project settings
    - run: pip -V
    - run: pip install -U ipdb
    - run: pyenv install -s $TOX_PY27
    - run: pyenv install -s $TOX_PY35
    - run: pyenv install -s $TOX_PY36
    - run: pyenv install -s $TOX_PY37
    - run: pyenv local $TOX_PY27 $TOX_PY35 $TOX_PY36 $TOX_PY37
    # Save dependency cache
    - save_cache:
        key: txclient-{{ .Branch }}-{{ epoch }}
        paths:
        - /pyenv/versions
    - run: tox -v --recreate
    # Teardown
    #   If you break your build into multiple jobs with workflows, you will
    #   probably want to do the parts of this that are relevant in each
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
